###########################
# Configuration for rubocop
#
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

MethodLength:
  Max: 200

LineLength:
  Max: 160

AlignParameters:
  Enabled: true

SpaceAroundOperators:
  Enabled: true

Encoding:
  Enabled: false

AndOr:
  Enabled: true

FinalNewline:
  Enabled: true

AssignmentInCondition:
  Enabled: true

AllCops:
  Excludes:
    - vendor/**
    - '**/node_modules/**'

ClassLength:
  Enabled: false

##
# TODO: enable and check everything below

RegexpLiteral:
  Enabled: false

AccessorMethodName:
  Enabled: false

NilComparison:
  Enabled: false

WhileUntilDo:
  Enabled: false

TrailingComma:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

RedundantBegin:
  Enabled: false

VariableName:
  Enabled: false

MethodName:
  Enabled: false

SignalException:
  Enabled: false

HashMethods:
  Enabled: false

NumericLiterals:
  Enabled: false

SpaceAfterMethodName:
  Enabled: false

DotPosition:
  Enabled: false

AlignArray:
  Enabled: false

ConditionPosition:
  Enabled: false

EmptyLiteral:
  Enabled: false

TrivialAccessors:
  Enabled: false

MultilineBlockChain:
  Enabled: false

PredicateName:
  Enabled: false

HashSyntax:
  Enabled: false

# Single Quotes
StringLiterals:
  Enabled: true

UnlessElse:
  Enabled: false

RedundantSelf:
  Enabled: false

WordArray:
  Enabled: false

IfUnlessModifier:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: true

WhileUntilModifier:
  Enabled: false

Semicolon:
  Enabled: true

BlockNesting:
  Enabled: true

Proc:
  Enabled: false

Lambda:
  Enabled: false

CollectionMethods:
  Enabled: false

EmptyLineBetweenDefs:
  Enabled: true

SpaceInsideHashLiteralBraces:
  Enabled: true

RescueException:
  Enabled: false

CaseIndentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: true

IndentationWidth:
  Enabled: true

# That would be nice to have - check for long methods
CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

AlignHash:
  Enabled: false

SpaceAroundBlockBraces:
  Enabled: true

SingleLineBlockParams:
  Enabled: false

BracesAroundHashParameters:
  Enabled: true
