language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
notifications:
  email:
    recipients:
      - mattjones@yieldbot.com
    on_success: change
    on_failure: always

gemfile:
  - gemfiles/rubocop
  - gemfiles/no_rubocop

script:
  - 'bundle exec rake default'

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rubocop
    - rvm: 1.9.2
      gemfile: gemfiles/rubocop
    - rvm: 1.9.3
      gemfile: gemfiles/no_rubocop
    - rvm: 2.0
      gemfile: gemfiles/no_rubocop
    - rvm: 2.1
      gemfile: gemfiles/no_rubocop
